### ISSUE TITLE
Abstract from metadata is "Do not pass capture variables as arguments"

### ISSUE THREAD

**Issue by robrwo** [trwyant/perl-Perl-Critic-Policy-ValuesAndExpressions-ProhibitFiletest_rwxRWX#1]
MetaCPAN shows the wrong abstract in module listings https://github.com/metacpan/metacpan-web/issues/2704

**Comment by trwyant** [comment]
Many thanks for the extremely quick pickup. Version 0.002 just went to PAUSE. Now all I need to do is come up with a test mechanism of some sort to make sure this doesn't happen again the next time I create a new module from an old one.
